import os
from dotenv import load_dotenv

# Carrega as variáveis do arquivo .env
load_dotenv()

# Configurações do Stripe
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
STRIPE_WEBHOOK_SECRET_MENSAL = os.getenv('STRIPE_WEBHOOK_SECRET_MENSAL')
STRIPE_WEBHOOK_SECRET_OPENCODE = os.getenv('STRIPE_WEBHOOK_SECRET_OPENCODE')
STRIPE_WEBHOOK_SECRET_PERSONALIZADO = os.getenv('STRIPE_WEBHOOK_SECRET_PERSONALIZADO') 